### ISSUE TITLE
希望添加一个类

### ISSUE THREAD

**Issue by adk23333** [Starry-OvO/aiotieba-reviewer#15]
**添加一个给其它程序调用并可控制开关的审查器类**

> #6  之前在弄的

**正在写一个有web界面的贴吧管理器**

我可以拉一个pr吗？还是作者自己写。

**Comment by adk23333** [comment]
> 

哪有前端boy，全栈🤣可以在我主页看到库，不整太复杂的，能用就行。主要功能其实是和Q群联合封禁，还有内容咨询。管理器是附带的。

**Comment by n0099** [comment]
那么请问qqbot和web前端有任何共同之处吗？

**Comment by Starry-OvO** [comment]
有没有什么预览之类的，我不是很懂js相关的

**Comment by adk23333** [comment]
> 有没有什么搭建教程之类的，我想看下预览，but我不是很懂js相关的东西

没整完，过段时间搞定，这段时间我也挺忙。就是希望给这个reviewer文件添加一个继承自线程类或者进程类的自定义类来方便其它py的脚本调用控制。（也是给我的后端）我自己整的那个关闭开启时会报错😂

**Comment by n0099** [comment]
经典现代前端娱乐圈人上壬

**Comment by langyo** [comment]
@n0099 姑且先别拉上我来干活了，为点鸡毛蒜皮的小事就全频段拉黑的话，我再好心也没这闲情逸致了——直到有些人重新学会交谈为止

备注：我能继续接黑兔的坑，看的是 430 的面子

**Comment by kokoro-aya** [comment]
1. 我很讨厌n9有事没事在issue里面聊些有的没的，把无关的事情非要扯到一起的做法。
2. 但我更讨厌网暴群友把群友的聊天转发出去批判一番还认为自己没问题的事情。您觉得是鸡毛蒜皮，我尊重您的想法。
3. 黑兔或者430和您的个人关系，关这个什么事情？
4. 是我做的决定，您没必要指责n9。我也不觉得有什么好谈的。
5. 无关内容我觉得还是适可而止，别污染其他人的repo。我建议和repo无关的人士unsubscribe相关thread。
6. off topic到此为止，我很不愿意污染别人的repo。

**Comment by Starry-OvO** [comment]
我确实有意做webui，但现在时间实在是不够，还有一个imghash库没动笔，研一课也多，这个webui更加遥遥无期

**Comment by kokoro-aya** [comment]
如果不指望短时间内就要上架的话我可以试试做webui，不过需要了解一下项目架构还有打算做什么样的设计了（比如说前后端怎么通信和约定），以及我也挺忙所以估计进展会非常慢

**Comment by Starry-OvO** [comment]
> 如果不指望短时间内就要上架的话我可以试试做webui，不过需要了解一下项目架构还有打算做什么样的设计了（比如说前后端怎么通信和约定），以及我也挺忙所以估计进展会非常慢

感觉以这个项目为基础做ui还是怪怪的，因为它一开始的设计目标就只是一个简单的脚手架，包含了大量的全局状态和奇葩的hook写法。二次开发还是建议以aiotieba为起点，虽然那个项目的api也不算非常稳定。
webui我想做的功能太多了，所以一直不想动手写，比如自定义规则、规则测试、数据库的管理、增强版的申诉界面。

**Comment by n0099** [comment]
> 姑且先别拉上我来干活了

您又有什么资格假定n0099于 https://github.com/Starry-OvO/aiotieba-reviewer/issues/15#issuecomment-1515727835 中野蛮假at阁下是为了提请`现代前端娱乐圈壬上壬伊欧神`立即使用`奥利金德rust-lang热潮`赋能`starry神版贴吧管理器`（现称`aiotieba`）？

---
> 为点鸡毛蒜皮的小事就全频段拉黑的话，我再好心也没这闲情逸致了——直到有些人重新学会交谈为止

> 1. 我很讨厌n9有事没事在issue里面聊些有的没的，把无关的事情非要扯到一起的做法。

截止2023年4月，您等四叶人们不会还认为n0099于2022年11月31号全网销号虚元（正如同`新创无际开发组迫真管理日面包` @sunbread 始终认定`新创无际rust人生信壬西兔人迺逸夫` @Prunoideae 于2022年退网虚元是由于`邪恶组织四叶重工驻新创无际间谍`n0099的长期迫害所致 https://github.com/n0099/TiebaMonitor/issues/32#issuecomment-1402693620 ）是由于维也纳阁下当时所声称的： https://t.me/s/n0099official/1807
> [@n0099_cn](https://t.me/n0099_cn) N0099发起的石家庄取消防疫变法失败让群众中的一小撮躺派大失所望，这些人煽风点火鼓动不明真相的清零派群众，在各地造成一些风波，这是正常现象。墙内的朋友们千万长点脑子，别被民逗轮子领导人n0099忽悠瘸了，网上和线下冲塔的事都别干，一堆人等着吃你人血馒头呢。你的牺牲除了给冲浪傻狗当谈资，给维稳人员找点事做涨业绩，没有任何意义。

亦或 https://t.me/s/n0099official/1651
> 重返四叶 平反橙猫 五大诉求 缺一不可
> 1. 在四叶重工所有分群为2022年以来遭遇政治迫害的橙猫道歉。
> 2. 成立独立调查组，彻底调查四叶皇帝irol所造成的无辜人士血案。
> 3. 解散以irol为首的小团体，公审以N9为首的四人帮官僚集团。
> 4. 取消四叶重工独裁制，实现四叶人真普选，四叶壬一人一票，泛银河系格雷科技邪恶组织的担当陈意志第三帝国人员可一人十票，无条件选举橙猫为主席并且终身连任。
> 5. 废除所有针对于炼铜相关的法律，接受杨博文调查组的监督，把真正的人权和自由还给陈意志第三帝国的无辜人士。

这类单一原因所致的吧？
事实核查：没有`430-四叶话语体系`自19年以来可持续性的魔怔玩网恶俗迫害，`邪恶组织四叶重工`不会从[2021年9月](https://t.me/n0099_tg/9552)开始至[2022年11月](https://t.me/s/n0099official/1798)花费整整一年时间才完成完全解体从而达成`仏国白左女权斗士irol阁下`所最反对的`最凶最恶超高校级`[社会原子化](https://en.wikipedia.org/wiki/Atomism_(social))超事件
而台谍430对此也早有预言：
[![image](https://user-images.githubusercontent.com/13030387/233434250-8db20998-5b2a-44b5-8888-42eea6b5b404.png)](https://t.me/s/n0099official/1765)
[![image](https://user-images.githubusercontent.com/13030387/233438615-805adb73-e553-45e2-ba1f-76bba9a2b911.png)](https://t.me/s/n0099official/1739)

---
> 2. 但我更讨厌网暴群友把群友的聊天转发出去批判一番还认为自己没问题的事情。您觉得是鸡毛蒜皮，我尊重您的想法。

而在`四叶头子CS硕士PLT理论中级高手仏皇irol阁下`于2023年3月正义驱逐`ra3日冕mod开发者现代前端娱乐圈壬上壬伊欧神`出`流亡四叶残部之里1群`后的2023年4月中，irol阁下选择了毫不留情地正义检举了同时叠加着她心目中两大讨厌特征的n0099，以进一步巩固其在`流亡四叶残部之里1群`的`四叶沙其马头子`地位
台谍430近期所解密的四叶网络内部通讯早已昭然若揭：
![image](https://user-images.githubusercontent.com/13030387/233439834-2e97900e-8b1e-4542-8fbe-1bc650eb7218.png)

---
> 3. 黑兔或者430和您的个人关系，关这个什么事情？

事实核查：在这`四叶小团体小圈子`中所有人所发的每一条消息所反应的所有事都是构成了关联的，而`四叶信安底层壬上壬上海贵族 FSF EFF 精神会员杨博文阁下` @yangbowen 也正是在看透了`邪恶组织四叶重工的罪恶本质`后立即选择彻底切割以避免被`四叶病毒`所感染：
[![image](https://user-images.githubusercontent.com/13030387/233441361-0d013760-e6ce-48c3-92bc-457d1bcbc673.png)](https://t.me/s/n0099official/1798)
[![image](https://user-images.githubusercontent.com/13030387/233442188-3f264b55-7561-495b-b56b-20e3722750ca.png)](https://t.me/s/n0099official/1676)

而四叶头子也于2022年11月进一步指出： https://t.me/n0099_tg/106101
## 我也懒得管n0099还是WangLingLing，说白了，死皮赖脸要骚扰别人也好，来来回回114进514出也好，对四叶有什么本质影响吗？只是体现了某人特别喜欢给自己加戏而已

已于2022年12月彻底虚元的[矩阵异常引路人neo](https://matrix.fandom.com/wiki/Neo)`维也纳阁下`更是为我们揭示了四叶的一切都不过只是台谍430于18年在台大患精分期间磕多了LSD所构造出的幻象
![image](https://user-images.githubusercontent.com/13030387/233443193-6d4cf452-802d-4054-b2d8-50ce30b03eea.png)
![image](https://user-images.githubusercontent.com/13030387/233442530-32bf2b3f-87b2-4c74-a70f-3dc9b77143d2.png)
## 不错，根本没有四叶重工这样[一个SC4插件作者](https://www.simcitychina.com/thread-31955-1-1.html)，但是只要四叶创始人qqbawh[印上几行字，伪造几张头像](https://www.simcitychina.com/thread-123876-1-1.html)，就可以马上使四叶存在

---
> 5. 无关内容我觉得还是适可而止，别污染其他人的repo。我建议和repo无关的人士unsubscribe相关thread。

irol阁下建议立即按照其正义屠杀7亿支那豚的思想
[![image](https://user-images.githubusercontent.com/13030387/233447859-550710bc-f459-4cde-8068-b6724634ee47.png)](https://t.me/s/n0099official/1744)
对`邪恶组织四叶重工炼铜本部叶独群组联合体叶独头子炼铜傻狗橙猫` @ChenNyan `作为元首领导下早已事实叶独的陈意志第三帝国无辜人士`进行一个subscribe的un
![image](https://user-images.githubusercontent.com/13030387/233445687-d00b076e-f0e2-4232-be79-fc398501ee44.png)

> 107607,2022-11-07T09:18:57+00:00,,……凡是瞒产私分者，一定都是一平、二调、三提款……一个是瞒产私分，一个是劳动力外逃，一个是麿洋工，一个是粮食伸手向上要，白天吃萝卜，晚上吃好的，我很赞成，这样做非常正确。你不等价交换，我就坚决抵制，河南分配给农民30％，瞒产私分15％，共45％，否则就过不了生活，这是保卫他们的神圣权利，极为正确。\n这两段言论看似截然不同，但当时任何一位官员在看到征购数字没有丝毫下调的迹象后，自然就明白了其中旨意，随着一场轰轰烈烈的“反瞒产”就在全国范围内开始了。
> 107608,2022-11-07T09:20:30+00:00,,这不就是现在的核酸封城
> 107609,2022-11-07T09:20:44+00:00,Au Rora,确实
> 107610,2022-11-07T09:23:47+00:00,Au Rora,超市赚的倒是不错这次疫情
> 107611,2022-11-07T09:23:55+00:00,,不如核酸公司
> 107612,2022-11-07T09:23:58+00:00,,不如大白
> 107613,2022-11-07T09:24:03+00:00,Au Rora,不过没有第一年封城赚的多了
> 107614,2022-11-07T09:24:23+00:00,,不如仏皇irol
> 107615,2022-11-07T09:24:27+00:00,,不如辉瑞
> 107616,2022-11-07T09:24:27+00:00,Au Rora,猪肉现在100块钱起送 不然不卖
> 107617,2022-11-07T09:24:29+00:00,,照我看来封城要大封特封
> 107618,2022-11-07T09:24:35+00:00,,不如石家庄以岭药业
> 107619,2022-11-07T09:24:57+00:00,,照irol看来屠杀7亿无辜人士要大图特图
> 107620,2022-11-07T09:25:25+00:00,Au Rora,
> 107621,2022-11-07T09:25:47+00:00,,？

> 107622,2022-11-07T09:25:57+00:00,,您又在断章取义
> 107623,2022-11-07T09:26:04+00:00,,此时此刻正如彼时彼刻
> 107624,2022-11-07T09:26:06+00:00,,您又在正义屠杀
> 107625,2022-11-07T09:26:16+00:00,,我理解为啥羊波纹对您不满了
> 107626,2022-11-07T09:26:21+00:00,,此时此刻正如彼时彼刻\n而irol对此早有预言：壬终将踏入同一条河流
> 107627,2022-11-07T09:26:54+00:00,,我理解为啥羊波纹对您不满了\n我理解为啥梨煌对您不满了
> 107628,2022-11-07T09:27:02+00:00,,对四叶不满了
> 107629,2022-11-07T09:27:25+00:00,,
> 107630,2022-11-07T09:38:56+00:00,吱 吱,

> 107633,2022-11-07T09:46:37+00:00,,我理解为啥梨煌对您不满了\n这就是原友的岁月史书与选择性遗忘
> 107634,2022-11-07T09:47:26+00:00,,我与N9都清晰记得七亿人言论 却找不到记录\n我怀疑是选择性清除了
> 107635,2022-11-07T09:48:00+00:00,,Zulip删除的消息后台能看见吗我不知道 只知道tg删除后的消息查无实据
> 107636,2022-11-07T10:11:17+00:00,,zulip也是删除没有记录
> 107637,2022-11-07T10:11:23+00:00,,是硬删除而不是软删除
> 107638,2022-11-07T10:11:34+00:00,,Zulip删除的消息后台能看见吗我不知道 只知道tg删除后的消息查无实据\ntg删除会在group actions log里留下
> 107639,2022-11-07T10:11:39+00:00,,但也只保留最近3天
> 107640,2022-11-07T10:12:05+00:00,,我与N9都清晰记得七亿人言论 却找不到记录 我怀疑是选择性清除了\n四叶真理部部长irol

> 108659,2022-11-08T11:50:46+00:00,,毫无疑问，橙猫是要化为乌有的。irol又想。她这么想时心中不免感到有些悲哀，尽管她明知橙猫瞧不起她，有点不喜欢她，而且完全有可能，只要她认为有理由，就会揭发她是个幼女强奸犯。反正，橙猫有什么不对头的地方，究竟什么地方不对头，她
> 也能说得头头是道。橙猫有着她所缺少的一些什么东西：情欲、癫狂、一种可以免于患难的愚蠢。你不能说她是不正统的。她相信四叶430语录体系的原则，她尊敬N9老阿姨，她欢庆胜利，她憎恨炼铜的异端者国男，不仅出于真心诚意，而且有着一种按捺不住的热情，了解最新的情况，而这是普通四叶壬所得不到的。…\n但是可以肯定的是，只要橙猫发觉她的——irol的——隐藏的思想，想要屠尽七亿支那人，那怕只有三秒钟，他也会马上向四叶内阁告发的
> 108660,2022-11-08T11:51:20+00:00,,
> 108661,2022-11-08T11:51:40+00:00,,？
> 108662,2022-11-08T11:51:48+00:00,,我说的是你国只有七亿人
> 108663,2022-11-08T11:51:59+00:00,,这就变成要图七亿人了？
> 108664,2022-11-08T11:52:14+00:00,,因为女权头子仏国白左irol认定剩下7亿女性不是壬
> 108665,2022-11-08T11:52:25+00:00,,这就变成要图七亿人了？\n支持正义屠杀7亿郭楠
> 108666,2022-11-08T11:52:39+00:00,,我什么时候说过这句话

---
> 8. off topic到此为止，我很不愿意污染别人的repo。

正如同2023年2月间`流亡四叶头子n0099`与四叶信安底层壬上壬上海贵族杨博文阁下`在某知名的又一个ofb web listing程序的pr https://github.com/SomeBottle/OdIndex/pull/21 中讨论了23条消息直至被
![image](https://user-images.githubusercontent.com/13030387/233445600-9b4504d6-b373-4a4b-9548-96956da1f733.png)

---
> 6. 我衷心祝愿黑兔那边一切顺利并且稳定运营，但我不认为四叶方面，无论是n9还是我，有能力、意愿和精力去继续维护。那边之后选择怎样去接管，是那边的事情，我也没有意愿去窥探。
> 7. 当然，我会合理的希望那边能够妥善的辨别和选择合作的伙伴。至于n9，我选择相信n9，而且这次也只是特例，我自己并没有任何干涉n9的项目的意愿。情理上我也支持黑兔和n9在条件允许的时候保持联系，这也不仅仅限于黑兔和n9之间。跑题了。

想必`四叶头子仏国白左女权斗士仏皇irol阁下`在某unity开发公司混过实习期业已从带pm和例会上学来了这套企业级pr（公关）话语体系以试图取代过去4年间对其造成了精神污染的`430-四叶话语体系`

## 雷恩第二大学的CS硕士，真以为丢了四叶带统领的光环以后自己还是个啥呢。
# 看，还在给自己加戏
> 106088,2022-11-06T12:07:16+00:00,yangbowen,我评价n9的话被断章取义转去，形成了误解。不过其实也不是很重要，我才懒得管 irol 还是 jrol 还是什么对我有何种误解。
> 106089,2022-11-06T12:07:16+00:00,yangbowen,可以作具体解释，但没有必要。那我只需要说，反正我跟`无辜人士`是一样的。
> 106090,2022-11-06T12:07:16+00:00,yangbowen,野蛮转发的n9，真以为丢了四叶带统领的光环以后自己还是个啥呢。
> 106091,2022-11-06T12:07:27+00:00,chen0430tw,新四人帮打算用键政取代炼铜，明眼人都能够看出来
> 106092,2022-11-06T12:07:27+00:00,Anonymous Telegram Bot,@kokoro_aya\n 群发言人你好，请问橙猫有在键政？谢谢
> 106093,2022-11-06T12:07:33+00:00,四叶重工官方频道,看，还在给自己加戏

---
> 备注：我能继续接黑兔的坑，看的是 430 的面子

`四叶沙其马ra3日冕mod开发者伊欧神`能够机械降神拯救受到`四叶解体超事件`影响的`缘之空吧资源贩子人民总理**屠夫` @ACGheitu 的`又一个wordpress站点`于 https://github.com/n0099/httpErrorPage/issues/2 https://github.com/n0099/tbclient.protobuf/issues/4 https://github.com/n0099/tbclient.protobuf/issues/5  之中，正是看的`kdays老管理gal圈皇帝台积电大股东牛顿与苹果树头子台谍430` @chen0430tw 曾于2021年在`时任四叶头子n0099`的介绍下帮助其致电某10年前的gal汉化组以取得修改授权

而这正如同2021年6~10月在批倒批臭了`430秧歌star`系`四叶四人帮`并协助解决`加州大学圣芭芭拉分校信安高材生ctf中级高手苏琦神对叶威胁`的`430作战计划指挥部`期间`伊欧神能继续接irol的四叶主群群主的坑，看的是430的面子` https://t.me/s/n0099official/1650
[![image](https://user-images.githubusercontent.com/13030387/233452271-8adfe934-4c8c-469c-92fe-9c619bd735bd.png)](https://t.me/s/n0099official/1656)
[![image](https://user-images.githubusercontent.com/13030387/233452426-3fb572e3-1455-47e2-91c9-451ced3d32a9.png)](https://t.me/s/n0099official/1658)
![image](https://user-images.githubusercontent.com/13030387/233452500-1a7304f7-d482-4335-960c-825300b997ac.png)

---
> 4. 是我做的决定，您没必要指责n9。我也不觉得有什么好谈的。

是`CS硕士irol阁下`于2023年3月16日所亲自指挥亲自部署亲自执行的`sudo apt purge nginx`，您没必要指责n9。他也不觉得有什么好谈的。
而由台谍430所解密的这一切消息片段所构成的逻辑链都印证了其为何要这么做

---

![image](https://user-images.githubusercontent.com/13030387/233453132-05a84adb-f586-49f6-bf7c-91525ad06f8e.png)

而这一切正如同`osu!4模式全能神 `@cdwcgt 于2022年3月被某些中国osu玩家嫉妒其全能pp成绩而jvbao至`Dean "peppy" Herbert`声称其开挂刷pp导致其被永封长达3个月后的个人签名所预言： https://osu.ppy.sh/users/14721101
![image](https://user-images.githubusercontent.com/13030387/233453848-8f760c90-43cc-4a62-8055-c48e96fc1064.png)

# 毁掉四叶的不一定是和430势不两立的430秧歌star，更可能是看起来人畜无害的炼铜傻狗橙猫

---
> 还有一个imghash库没动笔，研一课也多，这个webui更加遥遥无期

截止2023年4月，我仍未能知晓阁下在 https://github.com/Starry-OvO/aiotieba/pull/63#issuecomment-1474528124 中所实际落地的到底是何种算法在某个库中的特定实现

https://github.com/Starry-OvO/rotate-captcha-crack/commit/d9a726f48eb4daecaa4cb023d205e2284d57227c#diff-4c3a66ab23ccff61cff9c7582daaf202b36387977edeaed9a7232338e32e41fbR3 早已指出
> 因为准备发论文，故优先更新英文文档，中文文档仅保留使用方法就不介绍原理了

与此同时，截止2023年4月，n0099仍在与百度paddleocr和google tesseract所造成的内存溢出搏斗 https://github.com/sdcb/PaddleSharp/pull/42

---
> 如果不指望短时间内就要上架的话我可以试试做webui，不过需要了解一下项目架构还有打算做什么样的设计了（比如说前后端怎么通信和约定），以及我也挺忙所以估计进展会非常慢

`四叶头子CS硕士PLT理论中级高手仏皇irol阁下`在完成对其始于2022年10月的novelai大革命快速落地之 https://github.com/AUTOMATIC1111/stable-diffusion-webui 的全方位威胁评估后试图亲自下凡实际参与同为某个py项目的webui化过程，以进一步背弃其在2022年8月间于[四叶zulip](https://n0099.zulipchat.com/)与`新创无际HKUST留学生上海国资委编制内狗语言用户刘予顺神` @DWVoid 一同约定的对n0099自17年来持续开发的并于2021年使用c#大脑升级重写的爬虫核心部分 https://github.com/n0099/TiebaMonitor/tree/v2/crawler 逻辑添加遥测追踪上报至[普罗米修斯时序日志数据库](https://github.com/prometheus/prometheus)的史诗级任务

---
> 虽然那个项目的api也不算非常稳定

`四叶头子CS硕士PLT理论中级高手仏皇irol阁下`于 https://github.com/Starry-OvO/aiotieba/pull/88#issuecomment-1407514592 对此早有预言
> 我不了解python，我想如果穷尽贴吧的api做出一大堆对应的exception也是不切实际的想法。
而 https://github.com/Starry-OvO/aiotieba/issues/64 https://github.com/Starry-OvO/aiotieba/issues/77 以及`流亡四叶残部里1群`管理 @BANKA2017 所长期维护与tbm齐名的 https://github.com/BANKA2017/twitter-monitor 项目进一步阐明了此类试图追踪一切`api breaking changes without any warrant`猫鼠游戏的无尽本质

---
> webui我想做的功能太多了，所以一直不想动手写，比如自定义规则、规则测试、数据库的管理、增强版的申诉界面。

而这正如同n0099自17年来持续开发的 https://github.com/n0099/TiebaMonitor 为何在6年后失去了一切web界面导致其只能手写sql检索数据库的现状： https://tieba.baidu.com/p/8358519751?pid=147366666227#147366666227

**Comment by Prunoideae** [comment]
我仏了

**Comment by n0099** [comment]
> 我仏了

而早已于2022年7月向`邪恶组织四叶重工`宣战并加速了持续一年的`四叶解体超事件`的`奥利金德头子LG神` @Lasm_Gratel 也于2023年4月在`流亡四叶本部里1群`如此回应n0099当时指出曾于2021年被LG认证为`奥利金德魔怔mtf`的小沫已于近期同`邪恶组织四叶重工炼铜本部叶独群组联合体叶独头子炼铜傻狗橙猫` @ChenNyan 同居：
![image](https://user-images.githubusercontent.com/13030387/233460983-6bcd2b4c-6576-4fce-882a-163004de7424.png)

> 我服了

**Comment by ACGtutusang** [comment]
既然有提到我，我就稍微说一些：
首先呢，这条消息，如果四叶你和我之间没有什么意外情况的话，应该是最后一条消息，此后，我不会再寻求你的帮助或其他事务，非紧急情况下我也不会再主动和四叶你联系，当然，这个紧急情况，我想应该以后也不会出现，因为四叶对于我个人来说，只是依赖他的维修网站的能力，其他再无依赖；
下面说正事：
1.此次因为你们这个小圈子各种破事，导致的我站完全处于瘫痪不可用的状态，已长达数月，我完全是受害方，我甚至不知道四叶退网的原因，而且，我也不想和你们这个圈子有过于深度的交流，因为我只是一个黄油网站的站长，我是真他妈不想牵扯那么多，我只想稳定的运营我的网站，当然，这不是批判，我的意思是，你们自己的矛盾，自己解决，不要牵扯到我以及我的网站，四叶本人或者说围绕四叶展开的各种矛盾，不应该涉及到我，因为我只是一个黄油站长，我与你们这个圈子交流甚少，我完全不处于你们的矛盾点上，但是，以后的日子里，不管四叶是否回归，我都希望还能继续保持一个良好的正常的交流关系，而不是互相攻击阴阳怪气；
2.关于我站运维人员更换事宜，我想这不关irol和四叶的事，首先要搞明白我一直都说的诉求，那就是我要的是长久且稳定的运维，至于这个人（1o），是否和四叶，或者说和irol有什么矛盾，我完全不在乎，因为我他妈只是想把网站稳定的运行下去，而不是他妈的像求爷爷告奶奶的似的求着你去修BUG，我每天都上班，很累，所以我不想再和四叶你扯皮了；
就这样。

**Comment by kokoro-aya** [comment]
玩够了吗？

合着从头到尾就是故意的是吧。

我这段时间的情绪和精神状态都特别差了，一大堆事情堆到一起都烦死了，然后服务器三天两头炸。

您说我sudo purge nginx，要不要翻一下历史记录看看purge之前我在做啥？

要不要问一下我服务器上今天配置文件丢了明天certbot又没了是什么情况？

certbot没了，我想把certbot重装，结果提brotli版本错误，然后我想重装nginx，把conf搞丢了。

要说的话确实是我的责任，毕竟这种事情应该先备份的。

但您的被害妄想能不能别这么发散？

我本来就有严重的精神涣散，近期心态和情绪都很差，能不能体谅一下别人？三天两头炸服然后被人天天催，是人都会烦吧。我又是特别讨厌被人催的，烦到了极点就会顾此失彼。

不想给自己辩护，就是想说我很烦。

我没有举报你，当然，你肯定会怀疑我，一厢情愿到现在我才意识到跟你已经呗一层可悲的隔膜隔绝了。

要我怎么证明我没有举报？还是说，让您来证明我如何举报你？

有没有一种可能，如果我想举报你，那我早就关闭服务器，把你的权限删光，把群解散了。

我真的受够了这堆烂泥一样翻来倒去的车轱辘话了。

去他妈的qqbawh、模吧和430。到现在你还一点b数都没有吗？四叶存在的意义难道不是因为n0099这个人？不是因为那几个群里那些跟着你聊天的老人？

你知道我每次看到你扯那堆qqbawh之类的陈年烂芝麻都很难受吗？我tm在乎的是作为我的朋友的n9，而不是什么莫名其妙的模吧或者什么别的鬼玩意。

你去到哪里大家就跟你去哪里，你消失了人心就散了，这还不够明显吗，还要说什么四叶跟你无关，无关你mb呢。我留着那几个小群的唯一意义就是等你回群里然后大家好好的像以前那样聊天。

也别拿那堆可笑的形容词来玩cosplay，那个大统领我只见430用过，我什么时候用过了？

也别再拿430来压我了行不行，我算是看出来了，从那个屠杀群开始。

当初我就不该跟这堆人来往。

我真的受够这一切鬼东西了，另外能不能别tm转一大堆废料来把水越搅越混。转这一大堆乱七八糟的东西除了污染你的精神状态还有什么意义？

也不是说不让你视奸不让你转发。

但是说实话，从去年年底到现在，半年了，转发这一大堆废料，我只看到你的精神状态越来越差。

我很害怕。我不知道该怎么办。

我也很不想污染starry的repo。抱歉。

但是我真的受够了。

梨木和我都把你当朋友来看待的，能不能正眼对待一下我们？

**Comment by langyo** [comment]
怎么一个个都挺闲的，羡慕你们有时间能在这里长篇大论，不论说的什么东西……

我没空浪费时间，我还有很多事情没忙完

直接说结论

1. 我大体上支持 n9 的观点

2. irol 的个人精神问题并不应当由我买单，我再怎么圣母心也到此为止了

3. 黑兔的站点确实已经乱的惨不忍睹了，我已经在着手迁移数据换引擎了

**Comment by DWVoid** [comment]
中午喝个咖啡突然收到一大堆邮件，我还以为是什么事情。并不会推荐在issue上面吵无关的事情，看起来蛮累的
另外，如果有技术方面有需要的话我可以提供有限的帮助------------------------------------------------------------------
***@***.***>
日　期：2023年04月21日 08:03:48
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [Starry-OvO/aiotieba-reviewer] 希望添加一个类 (Issue #15)

怎么一个个都挺闲的，羡慕你们有时间能在这里长篇大论，不论说的什么东西……
我没空浪费时间，我还有很多事情没忙完
直接说结论 
我大体上支持 n9 的观点 
irol 的个人精神问题并不应当由我买单，我再怎么圣母心也到此为止了 
黑兔的站点确实已经乱的惨不忍睹了，我已经在着手迁移数据换引擎了
