### ISSUE TITLE
重新描述一下我的需求吧

### ISSUE THREAD

**Issue by adk23333** [Starry-OvO/aiotieba-reviewer#16]
原来的issue关了算了，能删吗emmm

我只是希望reviewer能添加一个导出而已，不想每次更新都改一次源码，而基于aiotieba从头写一个的话，我又没有足够的时间。如前一个issue里作者说的，reviewer的结构，我看的不是很懂emm，所以希望作者能添加一个给其它py程序调用的线程类或者类似功能的东西。

**Comment by n0099** [comment]
#14 #15

> 关了算了，能删吗

只能说互联网没有记忆，但archive.org和四叶贴吧云监控有。 
https://web.archive.org/web/20230421053443/https://github.com/Starry-OvO/aiotieba-reviewer/issues/15

**Comment by Starry-OvO** [comment]
我猜你需要一个类似`Scheme`的类来存放所有的审查策略，然后用一个类似`Scheme.run()`的东西来启动扫描？

**Comment by adk23333** [comment]
> 我猜你需要一个类似`Scheme`的类来存放所有的审查策略，然后用一个类似`Scheme.run()`的东西来启动扫描？

可以，大致是这样。
只要能给其它py文件引入并实例化，然后可以随时控制扫描的启动与关闭即可。

**Comment by n0099** [comment]
建议直接 https://en.wikipedia.org/wiki/Strategy_pattern https://en.wikipedia.org/wiki/Chain-of-responsibility_pattern

**Comment by Starry-OvO** [comment]
这个，我觉得我可能得9月往后才能有时间，我现在要做的东西包括
- 学光学
- 做完一个pv
- 开源一个轮廓匹配的项目
- 研究一下群签到
- 写一篇关于helioshash的文章
- 写一个imghash库
而且前三项还挺强制性的，所以...

**Comment by adk23333** [comment]
> 这个，我觉得我可能得9月往后才能有时间，我现在要做的东西包括
> 
> * 学光学
> * 做完一个pv
> * 开源一个轮廓匹配的项目
> * 研究一下群签到
> * 写一篇关于helioshash的文章
> * 写一个imghash库
>   而且前三项还挺强制性的，所以...

可以，能加上就行了，我这边进度也不会太快hhh。
