### ISSUE TITLE
example reviewer单独运行该文件时的报错

### ISSUE THREAD

**Issue by adk23333** [Starry-OvO/aiotieba-reviewer#18]
环境是py3.10
以及最新的aiotieba和reviewer
使用--no_test参数
报错如下
```
<2023-05-20 01:52:42.250> [WARN] [get_posts] Error parsing message. tid=6818218749
<2023-05-20 01:52:42.251> [WARN] [get_posts] Error parsing message. tid=8364486004
<2023-05-20 01:52:42.251> [WARN] [get_posts] Error parsing message. tid=8393777775
<2023-05-20 01:52:42.251> [WARN] [get_posts] Error parsing message. tid=8304877037
<2023-05-20 01:52:42.251> [WARN] [get_posts] Error parsing message. tid=6467983845
<2023-05-20 01:52:44.708> [WARN] [get_posts] Error parsing message. tid=8390314070
<2023-05-20 01:52:44.709> [WARN] [get_posts] Error parsing message. tid=8364486004
<2023-05-20 01:52:44.709> [WARN] [get_posts] Error parsing message. tid=8338062609
```

**Comment by adk23333** [comment]
还有我重构后的[web管理器项目](https://github.com/adk23333/tiebaAdmin)
在项目内报错之后又用例程试了，也报错

**Comment by Starry-OvO** [comment]
这个一般是ip最近请求次数太多导致的吧。我一开始以为和这个 https://github.com/Starry-OvO/aiotieba/issues/123 有关联

**Comment by adk23333** [comment]
> 这个一般是ip最近请求次数太多导致的吧。我一开始以为和这个 [Starry-OvO/aiotieba#123](https://github.com/Starry-OvO/aiotieba/issues/123) 有关联

现在是这个报错了，在test的情况下，是正常的no test就报以下错误，换了网络试验也是如此。
```
<2023-05-20 13:08:36.346> [WARN] [get_posts] Timeout to read. tid=6310389445
<2023-05-20 13:08:36.346> [WARN] [get_posts] Timeout to read. tid=8322878361
<2023-05-20 13:08:36.346> [WARN] [get_posts] Timeout to read. tid=8305409598
<2023-05-20 13:08:36.347> [WARN] [get_posts] Timeout to read. tid=7834300682
<2023-05-20 13:08:36.347> [WARN] [get_posts] Timeout to read. tid=8026909560
<2023-05-20 13:08:36.347> [WARN] [get_posts] Timeout to read. tid=8364486004
<2023-05-20 13:08:36.348> [WARN] [get_posts] Timeout to read. tid=8354058936
```
这次试验是直接copy例程了

**Comment by adk23333** [comment]
淦，找到问题了，昨天我的网页端的cookie里面STOKEN不知道为什么有两个，复制错了。。。

**Comment by n0099** [comment]
> Error parsing message
> 这个一般是ip最近请求次数太多导致的吧。

是protobuf接口？大概率是服务端偶然会返回的一坨html`为了保护您的账号安全和最佳的浏览体验，当前业务已经不支持IE8以下浏览器` https://github.com/n0099/TiebaMonitor/blob/9694b66200462c5377cf85aef687f21cfab33d71/c%23/crawler/src/Tieba/ClientRequester.cs#L52

> 我一开始以为和这个 [Starry-OvO/aiotieba#123](https://github.com/Starry-OvO/aiotieba/issues/123) 有关联

那个issue中目前只会是`110001未知错误`

**Comment by Starry-OvO** [comment]
怪了，`get_posts`跟STOKEN应该没有关系啊

**Comment by adk23333** [comment]
> 怪了，`get_posts`跟STOKEN应该没有关系啊

但换了个今天的网页里的STOKEN就好了，总之挺奇怪的🤔之后没复现了
还有你handler例程第254行，又漏了那三个参数没填

**Comment by Starry-OvO** [comment]
那三个参数刚改完了

**Comment by n0099** [comment]
经典相关即因果 https://en.wikipedia.org/wiki/Correlation_does_not_imply_causation
所以为什么爬帖子时要带上自己百度号的登录态cookie？您巴不得百度cdn网管注意到您在疯狂刷贴吧吗

**Comment by adk23333** [comment]
> 那三个参数刚改完了

不过最近还有另一个问题，虽然主要功能都能正常使用
`<2023-05-21 08:53:23.321> [WARN] [get_threads] (110004, ''). fname=****`
每一次扫描都有这个日志警告，扫描间隔是30s

**Comment by Starry-OvO** [comment]
reply to n0099: 有些功能只有带上BDUSS才有，比如楼中楼
reply to adk23333: 家庭ip很容易频繁，我几个服务器虽然偶尔有但不影响功能，当然我也不确定是不是我省参数导致的

**Comment by n0099** [comment]
> 有些功能只有带上BDUSS才有，比如楼中楼

您是说`主题帖回复贴列表`接口中附带的每层回复楼中楼？https://github.com/Starry-OvO/aiotieba/blob/2b8459f5da25d204cc58077a3480b8f0cc453048/aiotieba/client.py#L534
单独请求楼中楼接口是无需登录态的

> (110004, '')

110004是贴吧服务端response中的`error_code`值？`''`空字符串是他返回的`error_msg`？这类response的http status code是什么？[429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429)吗？

> 家庭ip很容易频繁，我几个服务器虽然偶尔有但不影响功能

然而国内归属地的ip请求域`c.tieba.baidu.com`的rqs限制是30rqs，而国外归属地ip只有10rps

**Comment by adk23333** [comment]
> reply to adk23333: 家庭ip很容易频繁，我几个服务器虽然偶尔有但不影响功能，当然我也不确定是不是我省参数导致的

我服务器是香港的，内地要备案麻烦，我试试把时间间隔调的更大。

**Comment by n0099** [comment]
> 服务器是香港的，内地要备案

您不建http站不需要备案只需要平台实名

> 把时间间隔调的更大

没有自动重试？

**Comment by adk23333** [comment]
> 您不建http站不需要备案只需要平台实名
>
准备建站的服务器，顺便搭一下这个
> 
> 没有自动重试？
>
Strray的reviewer例程直接照搬的，我不喜欢造轮子。这个例程的功能已经基本满足需求了。你看我的[仓库](https://github.com/adk23333/tiebaAdmin) 里的网页截图就知道需求又多简单了

**Comment by n0099** [comment]
# #starry神出席贴吧吧主大会 https://tieba.baidu.com/p/8400852408
