### ISSUE TITLE
AttributeError: __enter__

### ISSUE THREAD

**Issue by adk23333** [Starry-OvO/aiotieba-reviewer#22]
https://github.com/Starry-OvO/aiotieba-reviewer/blob/cea507f31f3eba86803bac9666623331a94104d0/examples/reviewer_example.py#L132C1-L132C1

`with tbr.no_test():`

现在这条语句会报出该错误

**Comment by adk23333** [comment]
之前遗漏了async

**Comment by n0099** [comment]
https://github.com/adk23333/tiebaAdmin/commit/860aac9c528999277807121a95d575e546bad6ae
