### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by adk23333** [Starry-OvO/aiotieba-reviewer#25]
为什么不添加sqlite作为用户权限数据库的备选项呢，而且事实上在检查记录里面是用了sqlite的

大部分中小型贴吧的审查压力应该用不着mysql的性能，而多开一个mysql数据库无疑提高了使用这个框架的服务器成本。

**Comment by Starry-OvO** [comment]
因为我没这个需求，而且实现起来相当麻烦——适配两个数据库后端还要保证一致性，还要加测试，又要考虑如何设计一个优雅的接口让用户可以针对不同的方法选择不同的后端

**Comment by adk23333** [comment]
> 因为我没这个需求，而且实现起来相当麻烦——适配两个数据库后端还要保证一致性，还要加测试，又要考虑如何设计一个优雅的接口让用户可以针对不同的方法选择不同的后端

好吧，我打算拉个PR使用tortoise-orm给它添加sqlite的支持

**Comment by Starry-OvO** [comment]
加依赖就不用提pr了，直接两个分支吧

**Comment by adk23333** [comment]
> 加依赖就不用提pr了，直接两个分支吧

好吧，我整一个新的分支
