### ISSUE TITLE
关于审查功能的实现的问题

### ISSUE THREAD

**Issue by adk23333** [Starry-OvO/aiotieba-reviewer#28]
源码有点散乱，没看懂你是怎么判断帖子是否已经审查过，以避免重复请求没变化的帖子的楼层。

**Comment by Starry-OvO** [comment]
以`Thread`为例，实现在这里。其实就是在executor外边包了层装饰器用来拦截重复检查。实现很糙（但是能用）
https://github.com/Starry-OvO/aiotieba-reviewer/blob/c9f07f50d6f49f4c698c87e8cfb0d3f700dc0a7e/aiotieba_reviewer/reviewer/thread/checker.py#L11-L31

**Comment by n0099** [comment]
> 还有个问题，每一楼的id还有楼中楼的id是独一无二的吗？或者只是在该吧内独一无二。

fid tid pid spid 百度uid都是全局唯一的
pid spid共享同一个id空间（因为13年引入的`楼中楼`（百度称subpost）本质上就是`回复贴`（百度称post））
